apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-scan-app
  labels:
    app: ci-scan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-scan
  template:
    metadata:
      labels:
        app: ci-scan
    spec:
      automountServiceAccountToken: true
      hostNetwork: true
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: ci-scan
          image: node:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          resources: {}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 5
